name: Dispatch CI

on:
  push:
  workflow_dispatch:
  # Every Tuesday,Wednesday at 1:00pm UTC
  # schedule:
  #   - cron: '0 13 * * 2,3'

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch CI
        #uses: silverstripe/gha-dispatch-ci@v1
        uses: emteknetnz/gha-dispatch-ci@main
