name: Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: emteknetnz/gha-tag-release@main
        with:
          sha: d1bb7a73ebeee96a3b315f86d1093bb5fca93b8b
          tag: mytag
          delete_existing: true
          release: true
          body: 'this is "q my body'
          generate_release_notes: true
