name: Test create issue

on:
  workflow_dispatch:

jobs:
  test-create-issue:
    name: Test create issue
    # Only run cron on the silverstripe account
    # if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
       
    steps:
      - name: Create issue
        uses: emteknetnz/gha-issue@main
        with:
          title: My issue title
          description: This text will appear in the body of the GitHub issue
