name: Update JS deps
on:
  # Run on a schedule once per quarter
  schedule:
    - cron:  '0 0 1 */3 *'
  workflow_dispatch:
jobs:
  update-js:
    runs-on: ubuntu-latest
    steps:
      - name: Update JS
        uses: emteknetnz/gha-update-js@main
